### ISSUE TITLE
facet_grid issue

### ISSUE THREAD

**Issue by meren** [mikabr/ggpirate#2]
I was very excited to see this, and immediately tried on a dataset that we are about to submit to a journal, but run into an issue. I hope it will be pretty easy for you to reproduce. Thanks for the lovely tool.

(the same data) with `geom_pirate`:

![image](https://user-images.githubusercontent.com/197307/31179296-e45c6614-a91b-11e7-8249-17692cbae284.png)

With `geom_boxplot` + `geom_jitter`:

![image](https://user-images.githubusercontent.com/197307/31179320-f706b436-a91b-11e7-93ed-a4dc43e77755.png)

Thanks,

**Comment by mikabr** [comment]
@meren thanks for the bug report – could you please submit a [reproducible example](http://reprex.tidyverse.org) of it?

**Comment by mikabr** [comment]
@meren this should be fixed now!
