### ISSUE TITLE
Support for no colour aesthetics

### ISSUE THREAD

**Issue by gpwilliams** [mikabr/ggpirate#4]
Previously, I was able to run the following code to produce greyscale plots:

`ggplot(mpg, aes(x = class, y = cty)) + 
geom_pirate()`

However, since updating a number of packages (including ggplot2) I get the error message:

> `position_jitterdodge()` requires at least one aesthetic to dodge by

I'd be grateful of a way to make default plots as before without the need for manually defining a colour aesthetic in the `ggplot()` or `geom_pirate()` calls. If this is currently possible and this error reflects a problem with my setup, I'd be happy to explore this further.

Thanks for this great package!

**Comment by mikabr** [comment]
This is an issue with `position_jitterdodge()`, unfortunately. I would recommend calling `geom_pirate()` with `points = FALSE`, and adding a separate geom of your own for the points.
